# Generated by Django 4.2.1 on 2023-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='dept',
            field=models.CharField(max_length=50),
        ),
    ]
