# Generated by Django 4.2.1 on 2023-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_studentprofile_dept_alter_teacherprofile_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ktu_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
