# Generated by Django 4.2.1 on 2023-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_studentprofile_ktu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ph',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sem',
            field=models.CharField(default='', max_length=2),
        ),
    ]
