# Generated by Django 4.2.1 on 2023-06-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_profile_pic',
            field=models.ImageField(blank=True, upload_to='templates/student_profile_pic'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_profile_pic',
            field=models.ImageField(blank=True, upload_to='templates/teacher_profile_pic'),
        ),
    ]
