# Generated by Django 4.2.1 on 2023-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_certificate_delete_cerficate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
